#cd /etc/ansible/
#hosts TEST_RGS_ASAs, SMZ_RGS_ASAs, ALL_RGS_ASAs, Wageworks_FWs
#ansible-playbook  asa_commands.yaml  --user=andr9996 --ask-pass
- hosts: TASCFWs
  gather_facts: no
  connection: local
  vars:
    ansible_become: no
    ansible_become_method: enable
    ansible_network_os: ios
    ansible_network_cli_ssh_type: libssh
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      authorize: yes
      auth_pass: "{{ ansible_password }}"
  tasks:
  - name: run show version command
    asa_command:
      commands:
#        - conf t
#        - object-group network TEST12345678
#        - end
#        - writ me
#        - show run object-group id TEST12345678
#        - show run boot
        - show version | i days|hours|years
    register: config
  - debug: msg="{{ config.stdout }}"
