---
#this is the encrypted version for backups
#cd /etc/ansible/
#hosts TEST_RGS_ASAs, SMZ_RGS_ASAs, ALL_RGS_ASAs, Wageworks_FWs
#ansible-playbook  asa_backup.yaml  --user=andr9996 --ask-pass
- hosts: TEST_RGS_ASAs:ALL_RGS_ASAs
  gather_facts: no
  connection: local
  vars:
    sudo: yes
    ansible_become: yes
    ansible_become_method: enable
    ansible_network_os: ios
    ansible_network_cli_ssh_type: libssh
    ansible_user: nsadmin
    ansible_password: password
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      authorize: yes
      auth_pass: "{{ ansible_password }}"
  tasks:
  - name: backing up ASAs..........
    asa_command:
      commands:
#        - show clock
        - more system:running-config
    register: config
  - name: Store the config to directory
    copy:
        content: "{{ config.stdout[0] }}"
        dest: /etc/ansible/Backups/{{ inventory_hostname }}_{{ ansible_host }}.txt
